name: weather_app
description: "Weather anywhere in the world"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  intl: any

  flutter_dotenv: ^5.2.1

  flutter_bloc: ^9.1.0
  equatable: ^2.0.7

  retrofit: ^4.4.2
  dio: ^5.8.0+1

  json_annotation: ^4.9.0

  geolocator: ^14.0.0

  weather: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  retrofit_generator: ^9.1.9
  json_serializable: ^6.9.4

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - .env